export const dashboard = <i className="fa-solid fa-house"></i>
export const transactions = <i className="fa-solid fa-credit-card"></i>
export const categories = <i class="fa-solid fa-tag"></i>
export const accounts = <i class="fa-solid fa-wallet"></i>
export const settings = <i class="fa-solid fa-gear"></i>
export const logout = <i class="fa-solid fa-sign-out"></i>
export const trend = <i class="fa-solid fa-money-bill-trend-up"></i>
export const expense = <i class="fa-solid fa-money-bill-transfer"></i>
export const money = <i class="fa-solid fa-money-bill"></i>
export const freelance = <i class="fa-solid fa-earth-americas"></i>
export const stocks = <i class="fa-solid fa-arrow-trend-up"></i>
export const bitcoin = <i class="fa-brands fa-bitcoin"></i>
export const piggy = <i class="fa-solid fa-piggy-bank"></i>
export const yt = <i class="fa-brands fa-youtube"></i>
export const card = <i class="fa-brands fa-cc-visa"></i>
export const users = <i class="fa-solid fa-users-between-lines"></i>
export const dollar = <i class="fa-solid fa-dollar-sign"></i>
export const calendar = <i class="fa-solid fa-calendar"></i>
export const comment = <i class="fa-solid fa-comment"></i>
export const plus = <i class="fa-solid fa-plus"></i>
export const trash = <i class="fa-solid fa-trash"></i>
export const signout = <i class="fa-solid fa-right-from-bracket"></i>
export const takeaway = <i class="fa-solid fa-utensils"></i>
export const clothing = <i class="fa-solid fa-shirt"></i>
export const book = <i class="fa-solid fa-book"></i>
export const food = <i class="fa-solid fa-bowl-food"></i>
export const medical = <i class="fa-solid fa-briefcase-medical"></i>
export const tv = <i class="fa-solid fa-tv"></i>
export const circle = <i class="fa-solid fa-circle"></i>